{% set name = "fscacher" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97e00842b19104a9f32cfd1346278b7d27a3ce4bc6cfa52ef8776ae54741144e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - appdirs
    - joblib

test:
  requires:
    - pytest
    - pytest-mock
  imports:
    - fscacher
    - fscacher.tests
  commands:
    - python -m pytest -vv --pyargs fscacher

about:
  home: https://github.com/con/fscacher
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Caching results of operations on heavy file trees
  description: |
    fscacher provides a cache & decorator for memoizing functions whose outputs
    depend upon the contents of a file argument.
  dev_url: https://github.com/con/fscacher

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
